---
include:
  - "**/*.rb"
  # if pwd = dragonruby-windows-amd64/mygame
  - "app/*.rb"
  - "../../dragonruby-yard-doc/*.rb"
# if pwd = dragonruby-windows-amd64/
# - "mygame/app/*.rb"
# - "../dragonruby-yard-doc/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  # - rubocop # don't care until the program is massive, and i get in da flow!
  # NOTE: even with this off, emacs seems to run rubocop via flycheck..
  #   - can disable by adding this to config.el
  #   - (remove-hook 'ruby-mode-hook #'rubocop-mode)
  # zed seemed to have better defaults.. or maybe it was just off?.. lol
  - require_not_found
# formatter:
#   rubocop:
#     cops: safe
#     except: []
#     only: []
#     extra_args: []
require_paths: []
plugins: []
max_files: 5000
